// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const db_url = process.env.DATABASE_URL as string;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "migrations",
    seed: 'npx tsx --watch prisma/seed.ts',
  },
  datasource: {
    url: db_url,
  },
});

